#pragma once
#define SSB_SUCCESS                     0

#define SSB_DM_ERROR_UNABLE_TO_CREATE   10001
#define SSB_DM_ERROR_INITDEVICE         10002
#define SSB_DM_ERROR_DATA_EVENT         10003
#define SSB_DM_ERROR_DEVICE_NOT_CLAIMED 10004
#define SSB_DM_ERROR_STARTSESSION       10005
#define SSB_DM_ERROR_STOPSESSION        10006
#define SSB_DM_ERROR_RELEASEDEVICE      10007
#define SSB_DM_ERROR_DESTROYWINDOW      10008
#define SSB_DM_ERROR_CLOSED             10009
#define SSB_DM_ERROR_METADATAERROR      10010
#define SSB_DM_ERROR_SCANWATCHINIT      10011
#define SSB_DM_ERROR_GETTINGIMAGE       10012
#define SSB_DM_ERROR_SET_CAMERA_NUMBER	10013
#define SSB_DM_ERROR_SETIMAGETYPE       10014
#define SSB_DM_ERROR_SCANWATCHRESET     10015
#define SSB_DM_ERROR_GETCAMERAINFO      10016
#define SSB_DM_ERROR_UVC_DISABLED		10017
#define SSB_DM_ERROR_SCALE_OFFLINE		10018
#define SSB_DM_ERROR_MODEL_NOTSUPPORTED 10019
#define SSB_DM_ERROR_FW_NOTSUPPORTED	10020
#define SSB_DM_ERROR_SCANWATCH_DISABLED	10021
#define SSB_DM_ERROR_INVAL_CAMERA_INFO	10022
#define SSB_DM_ERROR_DEVICE_OFFLINE		10023
#define SSB_DM_ERROR_REFRESH_DEVICE		10024

#define SSB_SYSTEM_INVALID_PARAMS		20001
#define SSB_SYSTEM_INVALID_INSTANCE		20002
#define SSB_SYSTEM_UNKNOWN_EXCEPTION    20003
#define SSB_SYSTEM_FAIL_COPY            20004
#define SSB_SYSTEM_FAIL_PROC_IMAGE      20005
#define SSB_SYSTEM_FAIL_INIT			20006
#define SSB_SYSTEM_FAIL_UNINT			20007
#define SSB_SYSTEM_FEATURE_DISABLED		20008 
#define SSB_SYSTEM_ERROR_OFFLINE		20009
#define SSB_SYSTEM_HIGH_CPU_USAGE		20010


#define SSB_PA_ERROR_INITIALIZE         50001
#define SSB_PA_ERROR_INSTANCE           50002
#define SSB_PA_ERROR_LOG_FILE           50003
#define SSB_PA_ERROR_IMAGE_COUNT        50004
#define SSB_PA_ERROR_INVALID_BUFF       50005
#define SSB_PA_ERROR_PROCESSING         50006
#define SSB_PA_ERROR_CAMERAINFO         50007
#define SSB_PA_ERROR_CONFIG				50008
#define SSB_PA_ERROR_NOT_SUPPORTED		50009


#define SSB_PLA_ERROR_INITIALIZE        80001
#define SSB_PLA_ERROR_INSTANCE          80002
#define SSB_PLA_ERROR_PROCESSING        80003
#define SSB_PLA_ERROR_INVALID_BUFF      80004
#define SSB_PLA_ERROR_TRAINING	        80005
#define SSB_PLA_ERROR_UPDATE_REF		80006
#define SSB_PLA_ERROR_GET_LIST			80007
#define SSB_PLA_ERROR_DELETE_LIST		80008
#define SSB_PLA_ERROR_RESET_ALL			80009
#define SSB_PLA_ERROR_RESET_ITEM		80010
#define SSB_PLA_ERROR_CAMERAINFO		80011
#define SSB_PLA_ERROR_GET_ITEM			80012
#define SSB_PLA_ERROR_NOT_SUPPORTED     80013

#define SSB_STATUS                      40000
#define SSB_STATUS_INITIALIZED          SSB_STATUS+1
#define SSB_STATUS_SUSPICIOUS           SSB_STATUS+2
#define SSB_STATUS_NONSUSPICIOUS        SSB_STATUS+3
#define SSB_STATUS_DEVICE_ONLINE		SSB_STATUS+4
#define SSB_STATUS_FEATURE_DISABLED		SSB_STATUS+5
#define SSB_STATUS_PROCESS_REQ          SSB_STATUS+6
#define SSB_STATUS_REQ_PRO_SUCCESS		SSB_STATUS+7
#define SSB_STATUS_ITEM_NOT_CENTER      SSB_STATUS+8
#define SSB_STATUS_CONFIG_MGS_RECIEVED	SSB_STATUS+9
#define SSB_STATUS_PLA_CONFIG_SUCCESS	SSB_STATUS+10
#define SSB_STATUS_PA_CONFIG_SUCCESS	SSB_STATUS+11


#define SSB_ERROR_STATUS				70000
#define SSB_STATUS_UNINITIALIZED        SSB_ERROR_STATUS+1
#define SSB_STATUS_PLA_ERROR            SSB_ERROR_STATUS+2
#define SSB_STATUS_PA_ERROR             SSB_ERROR_STATUS+3
#define SSB_STATUS_SYSTEM_ERROR         SSB_ERROR_STATUS+4
#define SSB_STATUS_FAIL_INIT			SSB_ERROR_STATUS+5
#define SSB_STATUS_CENDETECT_ERROR		SSB_ERROR_STATUS+6
#define SSB_STATUS_METADATA_NA          SSB_ERROR_STATUS+7
#define SSB_STATUS_DEVICE_OFFLINE       SSB_ERROR_STATUS+8
#define SSB_STATUS_IMAGESCANNER_ERR     SSB_ERROR_STATUS+9
#define SSB_STATUS_CONFIG_ERROR			SSB_ERROR_STATUS+10
#define SSB_STATUS_REQ_PRO_FAILED		SSB_ERROR_STATUS+11