#pragma once

#define SSB_COMM_SUCCESS					0

#define SSB_COMM_REG_ERROR_OPEN_FAILED		10000
#define SSB_COMM_REG_ERROR_QUERY_FAILED		10001

#define SSB_COMM_STATUS						40000
#define SSB_COMM_STATUS_PIPESER_ERROR		SSB_COMM_STATUS+1
#define SSB_COMM_STATUS_SSB_ERROR			SSB_COMM_STATUS+2
#define SSB_COMM_STATUS_PIPESER_RES_SENT	SSB_COMM_STATUS+3
#define SSB_COMM_STATUS_REQUEST_PROCESSED   SSB_COMM_STATUS+4
#define SSB_COMM_STATUS_PROCESSING_REQ		SSB_COMM_STATUS+5
#define SSB_COMM_STATUS_SSB_FAIL_INIT		SSB_COMM_STATUS+6
#define SSB_COMM_STATUS_SSB_SUCCESS_INIT	SSB_COMM_STATUS+7
#define SSB_COMM_STATUS_PIPESER_FAIL_INIT	SSB_COMM_STATUS+8
#define SSB_COMM_STATUS_PIPESER_SUCESS_INIT	SSB_COMM_STATUS+9
